import type { CollectionItem } from './item'
import { item } from './item'

// Animals (36).
export const ANIMALS: CollectionItem[] = [
  item(
    'fox',
    'animals',
    'Fox',
    'common',
    '🦊',
    'Foxes have such good hearing that they can hear small rodents moving underground before they dig. They wrap their long bushy tail around themselves like a blanket to keep warm.',
    'Lives in: forests and fields worldwide',
  ),
  item(
    'frog',
    'animals',
    'Frog',
    'common',
    '🐸',
    'Frogs breathe partly through their skin, which is why they need to stay damp. Baby frogs, called tadpoles, live underwater and breathe with gills.',
    'Lives in: ponds and wet forests',
  ),
  item(
    'hedgehog',
    'animals',
    'Hedgehog',
    'common',
    '🦔',
    'A hedgehog has about 5,000 spines, though they are soft at birth and harden within days. When scared, it curls into a tight, prickly ball.',
    'Lives in: gardens and hedgerows in Europe',
  ),
  item(
    'rabbit',
    'animals',
    'Rabbit',
    'common',
    '🐰',
    'Rabbits can see almost all the way around themselves without turning their head. Their strong back legs let them leap many times their own body length.',
    'Lives in: meadows and burrows worldwide',
  ),
  item(
    'duck',
    'animals',
    'Duck',
    'common',
    '🦆',
    "A duck's feathers are naturally waterproof, coated in oil from a gland near its tail. Ducklings can swim within hours of hatching.",
    'Lives in: ponds, rivers and lakes',
  ),
  item(
    'squirrel',
    'animals',
    'Squirrel',
    'common',
    '🐿️',
    'Squirrels bury nuts all over their territory and remember most hiding spots by smell. They help forests grow by planting seeds they forget.',
    'Lives in: trees in forests and parks',
  ),
  item(
    'deer',
    'animals',
    'Deer',
    'common',
    '🦌',
    'Deer can turn their ears separately to listen for danger from two directions at once. Male deer grow a brand new set of antlers every year.',
    'Lives in: woodlands and grasslands',
  ),
  item(
    'owl',
    'animals',
    'Owl',
    'common',
    '🦉',
    'Owls can turn their heads about 270 degrees because they have extra neck bones. Their soft feathers let them fly and hunt almost silently.',
    'Lives in: forests and barns at night',
  ),
  item(
    'honeybee',
    'animals',
    'Honeybee',
    'common',
    '🐝',
    'A honeybee visits dozens of flowers on a single trip to gather nectar and pollen. Bees dance in special patterns to tell each other where the best flowers are.',
    'Lives in: hives in fields and gardens',
  ),
  item(
    'ladybird',
    'animals',
    'Ladybird',
    'common',
    '🐞',
    "A ladybird's bright colours warn birds that it does not taste very nice. Each species has its own spot pattern, a bit like a uniform.",
    'Lives in: gardens and meadows',
  ),
  item(
    'sea-turtle',
    'animals',
    'Sea turtle',
    'common',
    '🐢',
    'Sea turtles can hold their breath for hours by slowing their heartbeat right down. Females often return to the very beach where they hatched to lay their own eggs.',
    'Lives in: warm oceans worldwide',
  ),
  item(
    'dolphin',
    'animals',
    'Dolphin',
    'common',
    '🐬',
    'Dolphins sleep with one half of their brain awake at a time, so they can keep breathing. They use clicks and whistles to find fish and talk to each other.',
    'Lives in: oceans and some rivers',
  ),
  item(
    'penguin',
    'animals',
    'Penguin',
    'common',
    '🐧',
    "Penguins can't fly, but they are brilliant swimmers, some reaching 35 km per hour underwater. Thick feathers and a layer of fat keep them warm in icy water.",
    'Lives in: Antarctica and southern coasts',
  ),
  item(
    'koala',
    'animals',
    'Koala',
    'uncommon',
    '🐨',
    'Koalas sleep up to 20 hours a day because eucalyptus leaves give them very little energy. Their fingerprints look so much like human ones that experts have to check them closely.',
    'Lives in: eucalyptus trees in Australia',
  ),
  item(
    'flamingo',
    'animals',
    'Flamingo',
    'uncommon',
    '🦩',
    'Flamingos are actually born grey, and turn pink from pigments in the shrimp and algae they eat. They can sleep standing on one leg without falling over.',
    'Lives in: lagoons in Africa and South America',
  ),
  item(
    'chameleon',
    'animals',
    'Chameleon',
    'uncommon',
    '🦎',
    'Chameleons change colour mostly to show their mood or talk to other chameleons, not just to hide. Each eye can look in a different direction at the same time.',
    'Lives in: forests in Madagascar and Africa',
    'Say: kuh-MEEL-yun',
  ),
  item(
    'sloth',
    'animals',
    'Sloth',
    'uncommon',
    '🦥',
    'Sloths move so slowly that algae grows on their fur, helping them blend into the trees. They only come all the way down to the ground about once a week.',
    'Lives in: rainforest trees in Central and South America',
  ),
  item(
    'octopus',
    'animals',
    'Octopus',
    'uncommon',
    '🐙',
    'An octopus has three hearts and can squeeze its whole soft body through a gap the size of its eye. It can also change colour in an instant to hide.',
    'Lives in: oceans worldwide',
  ),
  item(
    'seahorse',
    'animals',
    'Seahorse',
    'uncommon',
    '🐠',
    'Seahorses are one of the only animals where the father carries the babies, in a pouch on his belly. Many pairs stay loyal to each other through a whole breeding season.',
    'Lives in: seagrass meadows and coral reefs',
  ),
  item(
    'elephant',
    'animals',
    'Elephant',
    'common',
    '🐘',
    'Elephants use their trunks, which have no bones at all, for smelling, breathing, drinking, and gentle hugs. They are one of the few animals that can recognise themselves in a mirror.',
    'Lives in: savannas and forests in Africa and Asia',
  ),
  item(
    'giraffe',
    'animals',
    'Giraffe',
    'uncommon',
    '🦒',
    "A giraffe's tongue can be up to 45 cm long, perfect for reaching leaves high in the trees. They only need a few short hours of sleep a day.",
    'Lives in: savannas in Africa',
  ),
  item(
    'lion',
    'animals',
    'Lion',
    'common',
    '🦁',
    "A lion's roar can be heard up to 8 km away. Most of the hunting in a pride is done by the lionesses, working together as a team.",
    'Lives in: grasslands in Africa',
  ),
  item(
    'tiger',
    'animals',
    'Tiger',
    'uncommon',
    '🐯',
    'Every tiger has a one-of-a-kind stripe pattern, just like a human fingerprint. Their night vision is roughly six times better than ours.',
    'Lives in: forests in Asia',
  ),
  item(
    'polar-bear',
    'animals',
    'Polar bear',
    'uncommon',
    '🐻‍❄️',
    'Polar bears have black skin under fur that looks white but is actually see-through. Their fur and a thick layer of fat keep them warm in freezing water.',
    'Lives in: Arctic sea ice',
  ),
  item(
    'orca',
    'animals',
    'Orca',
    'uncommon',
    '🐋',
    'Orcas are actually the largest kind of dolphin, even though people often call them killer whales. Each pod has its own special set of calls, almost like a family language.',
    'Lives in: oceans worldwide',
  ),
  item(
    'hummingbird',
    'animals',
    'Hummingbird',
    'uncommon',
    '🐦',
    'Hummingbirds can beat their wings up to 80 times a second, letting them hover and even fly backwards. They must eat often, since hovering uses energy incredibly fast.',
    'Lives in: gardens and forests in the Americas',
  ),
  item(
    'red-panda',
    'animals',
    'Red panda',
    'rare',
    '🐾',
    'Red pandas have a false thumb, an extra wrist bone, to help them grip bamboo shoots. Their long bushy tail helps them balance while climbing trees.',
    'Lives in: mountain forests in China and Nepal',
  ),
  item(
    'poison-dart-frog',
    'animals',
    'Poison dart frog',
    'rare',
    '🐸',
    "A poison dart frog's bright colours warn other animals not to eat it. Frogs raised away from their wild rainforest diet are not poisonous at all.",
    'Lives in: rainforests in Central and South America',
  ),
  item(
    'snow-leopard',
    'animals',
    'Snow leopard',
    'rare',
    '🐆',
    'Snow leopards have huge paws that work like snowshoes on deep snow. Their thick tail can be almost as long as their body and wraps around them like a scarf.',
    'Lives in: mountains in Central Asia',
  ),
  item(
    'axolotl',
    'animals',
    'Axolotl',
    'rare',
    '🦎',
    'An axolotl can regrow a lost leg, tail, or even part of its heart. It usually keeps its gilled, tadpole-like look its whole life instead of growing up like other salamanders.',
    'Lives in: lakes near Mexico City',
    'Say: AK-suh-lot-ul',
  ),
  item(
    'pangolin',
    'animals',
    'Pangolin',
    'rare',
    '🐾',
    'A pangolin is covered in tough scales made of the same material as human fingernails. When frightened, it curls up into an armoured ball.',
    'Lives in: forests and grasslands in Africa and Asia',
    'Say: PAN-goh-lin',
  ),
  item(
    'giant-panda',
    'animals',
    'Giant panda',
    'rare',
    '🐼',
    'Giant pandas eat bamboo for up to 12 hours a day and can eat over 12 kg of it. A newborn panda cub is smaller than a stick of butter.',
    'Lives in: bamboo forests in China',
  ),
  item(
    'kakapo',
    'animals',
    'Kakapo',
    'epic',
    '🦜',
    'A kakapo is a large, flightless parrot from New Zealand that smells a bit like honey. It can live for 90 years, one of the longest-lived birds known.',
    'Lives in: forests on islands in New Zealand',
    'Say: KAH-kah-poh',
  ),
  item(
    'okapi',
    'animals',
    'Okapi',
    'epic',
    '🦓',
    'The okapi looks like a mix of a zebra and a giraffe, and it is actually a close cousin of the giraffe. It stayed unknown to scientists outside Africa until the early 1900s.',
    'Lives in: rainforests in Central Africa',
    'Say: oh-KAH-pee',
  ),
  item(
    'narwhal',
    'animals',
    'Narwhal',
    'epic',
    '🐳',
    "A narwhal's long spiral tusk is actually an overgrown tooth, mostly found on males. Scientists think it may help them sense changes in the water around them.",
    'Lives in: Arctic ocean waters',
    'Say: NAR-wal',
  ),
  item(
    'blue-whale',
    'animals',
    'Blue whale',
    'legendary',
    '🐋',
    'The blue whale is the largest animal ever known to have lived, even bigger than any dinosaur. Its heart alone can weigh as much as a small car.',
    'Lives in: oceans worldwide',
  ),
  // --- Round 16 additions
  item(
    'otter',
    'animals',
    'Otter',
    'common',
    '🦦',
    'Sea otters hold hands while they sleep so they do not drift apart. Each otter also keeps a favourite rock to crack open shellfish.',
    'Lives in: coastal waters of the North Pacific',
  ),
  item(
    'kangaroo',
    'animals',
    'Kangaroo',
    'common',
    '🦘',
    "A kangaroo can hop faster than a car in a school zone, and it uses its big tail for balance. Baby kangaroos, called joeys, grow up in their mother's pouch.",
    'Lives in: grasslands and forests of Australia',
  ),
  item(
    'zebra',
    'animals',
    'Zebra',
    'common',
    '🦓',
    'Every zebra has its own stripe pattern, just like your fingerprints are only yours. Baby zebras can stand and walk within about an hour of being born.',
    'Lives in: grasslands of Africa',
  ),
  item(
    'meerkat',
    'animals',
    'Meerkat',
    'common',
    '🦡',
    'Meerkats take turns standing guard on their back legs and watching for danger. When they spot a threat, they bark a warning to the whole family.',
    'Lives in: deserts and dry plains of southern Africa',
  ),
  item(
    'crab',
    'animals',
    'Crab',
    'common',
    '🦀',
    'Crabs walk sideways because of the way their legs bend. Every year, millions of red crabs on Christmas Island march from the forest to the sea.',
    'Lives in: oceans, shores, and some islands',
  ),
  item(
    'snail',
    'animals',
    'Snail',
    'common',
    '🐌',
    'A snail carries its shell on its back, and the shell grows bigger as the snail grows. A snail moves on one big muscle called a foot, leaving a trail of slime behind.',
    'Lives in: gardens and woods around the world',
  ),
  item(
    'capybara',
    'animals',
    'Capybara',
    'uncommon',
    '🐹',
    'The capybara is the biggest rodent in the world, and it loves to swim and soak in water. Birds and even monkeys sometimes sit on its back, and it does not mind.',
    'Lives in: wetlands of South America',
    'Say: kap-ih-BAR-uh',
  ),
  item(
    'jellyfish',
    'animals',
    'Jellyfish',
    'uncommon',
    '🪼',
    'Jellyfish have no brain, no heart, and no bones, yet they have drifted in the sea for hundreds of millions of years. Their bodies are mostly water.',
    'Lives in: oceans everywhere',
  ),
  item(
    'manta-ray',
    'animals',
    'Manta ray',
    'uncommon',
    '🐟',
    'A manta ray can be wider than a car, and it flaps its fins like wings to glide through the sea. Even so, it eats only tiny creatures that it filters from the water.',
    'Lives in: warm oceans around the world',
  ),
  item(
    'komodo-dragon',
    'animals',
    'Komodo dragon',
    'uncommon',
    '🐉',
    'The Komodo dragon is the biggest lizard in the world and can grow longer than a bed. It smells with its forked tongue and can find food from far away.',
    'Lives in: a few islands in Indonesia',
  ),
  item(
    'platypus',
    'animals',
    'Platypus',
    'rare',
    '🦆',
    'The platypus has a duck-like bill, a beaver-like tail, and it lays eggs, even though it is a mammal. Under water, it finds its food by sensing tiny electric signals.',
    'Lives in: rivers and streams of eastern Australia',
  ),
  item(
    'quokka',
    'animals',
    'Quokka',
    'rare',
    '😊',
    'The quokka looks like it is always smiling, and it is sometimes called the happiest animal in the world. It is a small kangaroo cousin that lives on islands near Western Australia.',
    'Lives in: Rottnest Island and nearby, Australia',
    'Say: KWOK-uh',
  ),
  item(
    'tarsier',
    'animals',
    'Tarsier',
    'rare',
    '👀',
    "A tarsier's eyes are so big that each one is as large as its whole brain. It cannot move its eyes, so it turns its head almost all the way around instead.",
    'Lives in: forests of Southeast Asia',
  ),
  item(
    'aye-aye',
    'animals',
    'Aye-aye',
    'epic',
    '🐒',
    'The aye-aye taps on trees with one long thin finger and listens for grubs hiding inside. Then it gnaws a small hole and fishes the grubs out.',
    'Lives in: rainforests of Madagascar',
    'Say: EYE-eye',
  ),
]
