import type { CollectionItem } from './item'
import { item } from './item'

// Birds (24).
export const BIRDS: CollectionItem[] = [
  item(
    'european-robin',
    'birds',
    'European robin',
    'common',
    '🐦',
    'European robins are fiercely territorial and will even fight their own reflection. Both males and females have the bright orange-red breast, and they sing all year round.',
    'Lives in: gardens and woods across Europe',
  ),
  item(
    'blue-tit',
    'birds',
    'Blue tit',
    'common',
    '🐦',
    'Blue tits can hang upside down from thin twigs to find insects. Their blue cap shines in ultraviolet light that humans cannot see.',
    'Lives in: gardens and woods across Europe',
  ),
  item(
    'house-sparrow',
    'birds',
    'House sparrow',
    'common',
    '🐦',
    'House sparrows like to live close to people and often nest in holes in walls and roofs. They take dust baths, flapping about in dry dirt to stay clean.',
    'Lives in: towns, farms and gardens worldwide',
  ),
  item(
    'barn-swallow',
    'birds',
    'Barn swallow',
    'common',
    '🐦',
    'Barn swallows fly all the way from Europe to Africa for the winter, and back again in spring. They scoop up mud to build a little cup-shaped nest under a roof.',
    'Lives in: open fields and farms worldwide',
  ),
  item(
    'mute-swan',
    'birds',
    'Mute swan',
    'common',
    '🦢',
    "A mute swan can weigh as much as a medium-sized dog, which makes it one of the heaviest flying birds. Its babies are called cygnets and often ride on their parents' backs.",
    'Lives in: lakes and slow rivers in Europe and Asia',
  ),
  item(
    'canada-goose',
    'birds',
    'Canada goose',
    'common',
    '🦆',
    'Canada geese fly in a V shape, and the birds take turns leading at the front. They honk to keep the whole flock together.',
    'Lives in: lakes, parks and fields in North America and Europe',
  ),
  item(
    'herring-gull',
    'birds',
    'Herring gull',
    'common',
    '🐦',
    'Herring gulls can drink salty seawater, because special glands near their eyes get rid of the extra salt. They drop shellfish onto hard ground to crack them open.',
    'Lives in: coasts and harbours in Europe and North America',
  ),
  item(
    'great-spotted-woodpecker',
    'birds',
    'Great spotted woodpecker',
    'common',
    '🐦',
    'A great spotted woodpecker hammers on trees to find insects and to send loud drumming messages. Its strong skull and stiff tail feathers help it cling on and take the knocks.',
    'Lives in: woods and gardens across Europe and Asia',
  ),
  item(
    'blue-jay',
    'birds',
    'Blue jay',
    'common',
    '🐦',
    'Blue jays can copy the call of a hawk. Their feathers are not truly blue, because tiny structures in them bounce blue light back to our eyes.',
    'Lives in: oak woods and gardens in eastern North America',
  ),
  item(
    'northern-cardinal',
    'birds',
    'Northern cardinal',
    'common',
    '🐦',
    'Only the male northern cardinal is bright red, while the female is soft brown with a touch of red. Both of them sing, which is unusual for female songbirds.',
    'Lives in: gardens and woodland edges in North America',
  ),
  item(
    'kingfisher',
    'birds',
    'Kingfisher',
    'uncommon',
    '🐦',
    'A kingfisher dives headfirst into streams to snatch small fish. It bangs each fish against a branch before swallowing it headfirst.',
    'Lives in: rivers and lakes across Europe and Asia',
  ),
  item(
    'puffin',
    'birds',
    'Atlantic puffin',
    'uncommon',
    '🐦',
    'An Atlantic puffin can hold many small fish crosswise in its beak at once. It nests in a burrow and flaps its wings up to 400 times a minute.',
    'Lives in: sea cliffs and the North Atlantic Ocean',
  ),
  item(
    'peacock',
    'birds',
    'Peacock',
    'uncommon',
    '🦚',
    'Only the male peacock has the big shimmering tail, and he fans out more than a hundred long feathers to impress a peahen. The female is called a peahen.',
    'Lives in: forests and villages in India and Sri Lanka',
  ),
  item(
    'toco-toucan',
    'birds',
    'Toco toucan',
    'uncommon',
    '🦜',
    'The toco toucan has the biggest beak for its size of any bird, yet it is light because it is full of tiny air pockets. The beak also helps it get rid of extra heat to stay cool.',
    'Lives in: forests and woodland in South America',
    'Say: TOH-koh too-KAN',
  ),
  item(
    'bald-eagle',
    'birds',
    'Bald eagle',
    'uncommon',
    '🦅',
    'A bald eagle is not really bald, because its head is covered in white feathers. Its nest can weigh as much as a small car after years of adding more sticks.',
    'Lives in: lakes, rivers and coasts in North America',
  ),
  item(
    'scarlet-macaw',
    'birds',
    'Scarlet macaw',
    'uncommon',
    '🦜',
    'Scarlet macaws can live for 50 years or more and often stay with the same partner for life. Their long tail makes up about half of their body length.',
    'Lives in: rainforests in Central and South America',
  ),
  item(
    'snowy-owl',
    'birds',
    'Snowy owl',
    'uncommon',
    '🦉',
    'Snowy owls have feathers all the way down to their toes to keep them warm in the Arctic. Unlike most owls, they often hunt in the daytime.',
    'Lives in: the Arctic tundra',
  ),
  item(
    'mandarin-duck',
    'birds',
    'Mandarin duck',
    'rare',
    '🦆',
    'A male mandarin duck has orange sail feathers on his back and a rainbow of colours. These ducks nest in holes in trees, and the ducklings jump to the ground when they are about a day old.',
    'Lives in: wooded ponds and rivers in East Asia',
  ),
  item(
    'quetzal',
    'birds',
    'Resplendent quetzal',
    'rare',
    '🐦',
    'A male resplendent quetzal grows tail feathers up to a metre long in the breeding season. The ancient Maya and Aztec people treasured its shiny green feathers.',
    'Lives in: misty mountain forests in Central America',
    'Say: KET-sahl',
  ),
  item(
    'shoebill',
    'birds',
    'Shoebill',
    'rare',
    '🐦',
    'A shoebill has a huge beak shaped like a wooden clog, and it can stand almost still for ages waiting for a fish. It makes a clattering sound by clapping its beak.',
    'Lives in: swamps and marshes in central Africa',
  ),
  item(
    'secretary-bird',
    'birds',
    'Secretary bird',
    'rare',
    '🦅',
    'Secretary birds hunt snakes by stamping on them with their long, strong legs. The feathers on their head look like old-fashioned quill pens tucked behind an ear.',
    'Lives in: grasslands and savannas in Africa',
  ),
  item(
    'bird-of-paradise',
    'birds',
    'Raggiana bird-of-paradise',
    'epic',
    '🦜',
    'Male Raggiana birds-of-paradise dance on a branch, fanning out long flowing orange plumes to impress a female. It is the national bird of Papua New Guinea and appears on its flag.',
    'Lives in: rainforests in Papua New Guinea',
    'Say: rag-ee-AH-na',
  ),
  item(
    'kiwi',
    'birds',
    'Kiwi',
    'epic',
    '🐦',
    'The kiwi cannot fly, and it sniffs out worms with nostrils at the very tip of its long beak. A mother kiwi lays an egg that is huge compared with her body.',
    'Lives in: forests in New Zealand',
  ),
  item(
    'harpy-eagle',
    'birds',
    'Harpy eagle',
    'legendary',
    '🦅',
    "Harpy eagles have talons about as long as a bear's claws, and they snatch sloths and monkeys from the treetops. The feathers on their head can rise up like a crown.",
    'Lives in: rainforests in Central and South America',
  ),
]
