import type { CollectionItem } from './item'
import { item } from './item'

// Countries (30): one iconic landmark photo per country.
//  - where: "Capital: <city> · Continent: <continent>"
//  - emoji: the country flag emoji
export const COUNTRIES: CollectionItem[] = [
  item(
    "country-united-states",
    'countries',
    "United States",
    'common',
    "🇺🇸",
    "The Statue of Liberty stands on an island in New York Harbor and was a gift from France. The Grand Canyon in Arizona is so deep that many skyscrapers could be stacked inside it.",
    "Capital: Washington, D.C. · Continent: North America",
  ),
  item(
    "country-canada",
    'countries',
    "Canada",
    'common',
    "🇨🇦",
    "Canada has more lakes than any other country in the world. Its flag has a red maple leaf, and maple trees give us sweet maple syrup.",
    "Capital: Ottawa · Continent: North America",
  ),
  item(
    "country-united-kingdom",
    'countries',
    "United Kingdom",
    'common',
    "🇬🇧",
    "Big Ben is the nickname of the giant bell inside the clock tower in London. Tower Bridge opens in the middle so tall ships can sail underneath.",
    "Capital: London · Continent: Europe",
  ),
  item(
    "country-france",
    'countries',
    "France",
    'common',
    "🇫🇷",
    "The Eiffel Tower in Paris is made of iron and is repainted about every seven years. French bakers make long, crusty loaves called baguettes and soft, buttery croissants.",
    "Capital: Paris · Continent: Europe",
  ),
  item(
    "country-italy",
    'countries',
    "Italy",
    'common',
    "🇮🇹",
    "Italy is shaped like a big boot and is where pizza and pasta come from. In Rome, the Colosseum is an ancient arena that is nearly two thousand years old.",
    "Capital: Rome · Continent: Europe",
  ),
  item(
    "country-china",
    'countries',
    "China",
    'common',
    "🇨🇳",
    "The Great Wall of China winds across hills and mountains for thousands of kilometres. Giant pandas live in the bamboo forests of China and munch bamboo all day.",
    "Capital: Beijing · Continent: Asia",
  ),
  item(
    "country-japan",
    'countries',
    "Japan",
    'common',
    "🇯🇵",
    "Mount Fuji is Japan's tallest mountain, and its top is covered in snow in winter. Japan has super-fast bullet trains that zoom past at very high speed.",
    "Capital: Tokyo · Continent: Asia",
  ),
  item(
    "country-india",
    'countries',
    "India",
    'common',
    "🇮🇳",
    "The Taj Mahal is a beautiful white marble tomb that took about twenty years to build. India is home to wild Bengal tigers and big, gentle elephants.",
    "Capital: New Delhi · Continent: Asia",
  ),
  item(
    "country-australia",
    'countries',
    "Australia",
    'common',
    "🇦🇺",
    "Australia is both a country and a whole continent, and koalas live in the wild nowhere else. The Sydney Opera House has a roof shaped like giant white sails.",
    "Capital: Canberra · Continent: Oceania",
  ),
  item(
    "country-brazil",
    'countries',
    "Brazil",
    'common',
    "🇧🇷",
    "A huge statue called Christ the Redeemer watches over the city of Rio de Janeiro from a mountaintop. Brazil is home to most of the Amazon rainforest, with its toucans and jaguars.",
    "Capital: Brasília · Continent: South America",
  ),
  item(
    "country-mexico",
    'countries',
    "Mexico",
    'common',
    "🇲🇽",
    "Long ago, the Maya people built a stepped pyramid called El Castillo at Chichen Itza. Mexico is where chocolate and tortillas first came from.",
    "Capital: Mexico City · Continent: North America",
  ),
  item(
    "country-egypt",
    'countries',
    "Egypt",
    'common',
    "🇪🇬",
    "The Great Pyramids of Giza were built as tombs for kings more than four thousand years ago. The mighty Nile River flows through Egypt, and it is one of the longest rivers in the world.",
    "Capital: Cairo · Continent: Africa",
  ),
  item(
    "country-germany",
    'countries',
    "Germany",
    'uncommon',
    "🇩🇪",
    "Neuschwanstein Castle looks like a castle from a fairy tale and sits high on a hill in Germany. The Black Forest in Germany is where cuckoo clocks come from.",
    "Capital: Berlin · Continent: Europe",
  ),
  item(
    "country-spain",
    'countries',
    "Spain",
    'uncommon',
    "🇪🇸",
    "The Sagrada Família in Barcelona is a church with tall towers that people have been building for over one hundred years. In Spain, people eat a late dinner and love lively festivals.",
    "Capital: Madrid · Continent: Europe",
  ),
  item(
    "country-greece",
    'countries',
    "Greece",
    'uncommon',
    "🇬🇷",
    "The Parthenon is an ancient temple on a hill in Athens, built about twenty-five hundred years ago. Greece has thousands of islands with white houses and bright blue seas.",
    "Capital: Athens · Continent: Europe",
  ),
  item(
    "country-south-africa",
    'countries',
    "South Africa",
    'uncommon',
    "🇿🇦",
    "Table Mountain in Cape Town has a flat top that often wears a cloud like a tablecloth. South Africa is home to penguins that waddle on its beaches.",
    "Capital: Pretoria · Continent: Africa",
  ),
  item(
    "country-kenya",
    'countries',
    "Kenya",
    'uncommon',
    "🇰🇪",
    "Every year, huge herds of wildebeest and zebras travel across the Maasai Mara in Kenya. Kenya is a great place to see lions, elephants and giraffes in the wild.",
    "Capital: Nairobi · Continent: Africa",
    "Say: KEN-yuh",
  ),
  item(
    "country-thailand",
    'countries',
    "Thailand",
    'uncommon',
    "🇹🇭",
    "Thailand has glittering temples called wats, and elephants are a symbol of the country. The name Thailand means land of the free.",
    "Capital: Bangkok · Continent: Asia",
  ),
  item(
    "country-peru",
    'countries',
    "Peru",
    'uncommon',
    "🇵🇪",
    "High in the Andes mountains, the Inca built a mountain town called Machu Picchu long ago. Peru is home to fluffy llamas and alpacas.",
    "Capital: Lima · Continent: South America",
  ),
  item(
    "country-turkey",
    'countries',
    "Turkey",
    'uncommon',
    "🇹🇷",
    "Many hot air balloons float over the rocky valleys of Cappadocia in Turkey every morning. The city of Istanbul sits on two continents at the same time.",
    "Capital: Ankara · Continent: Asia and Europe",
  ),
  item(
    "country-south-korea",
    'countries',
    "South Korea",
    'uncommon',
    "🇰🇷",
    "Gyeongbokgung is a grand royal palace in Seoul that is over six hundred years old. Korea is famous for kimchi, tasty food made from spicy fermented cabbage.",
    "Capital: Seoul · Continent: Asia",
  ),
  item(
    "country-iceland",
    'countries',
    "Iceland",
    'rare',
    "🇮🇸",
    "Iceland is called the land of fire and ice because it has volcanoes, hot springs and glaciers. On dark winter nights, you can often see green northern lights dancing in the sky.",
    "Capital: Reykjavik · Continent: Europe",
  ),
  item(
    "country-new-zealand",
    'countries',
    "New Zealand",
    'rare',
    "🇳🇿",
    "New Zealand is home to the kiwi, a small bird with shaggy feathers that cannot fly. It has more sheep than people, and it has beautiful fiords like Milford Sound.",
    "Capital: Wellington · Continent: Oceania",
  ),
  item(
    "country-norway",
    'countries',
    "Norway",
    'rare',
    "🇳🇴",
    "Norway has deep fjords, which are long sea inlets with steep cliffs on both sides. In summer in the far north, the sun barely sets, so it stays light all night.",
    "Capital: Oslo · Continent: Europe",
  ),
  item(
    "country-morocco",
    'countries',
    "Morocco",
    'rare',
    "🇲🇦",
    "Aït Benhaddou is an old Moroccan town built of red clay at the edge of the desert. Part of the huge Sahara Desert is in Morocco, and you can ride camels there.",
    "Capital: Rabat · Continent: Africa",
    "Say: muh-ROCK-oh",
  ),
  item(
    "country-nepal",
    'countries',
    "Nepal",
    'rare',
    "🇳🇵",
    "Mount Everest, the tallest mountain on Earth, is on the border of Nepal. The great white stupa in Kathmandu has painted eyes that look out in every direction.",
    "Capital: Kathmandu · Continent: Asia",
    "Say: nuh-PAWL",
  ),
  item(
    "country-madagascar",
    'countries',
    "Madagascar",
    'epic',
    "🇲🇬",
    "Madagascar is a giant island where ring-tailed lemurs live, and they live nowhere else in the wild. Its giant baobab trees look like they are growing upside down.",
    "Capital: Antananarivo · Continent: Africa",
    "Say: mad-uh-GAS-kar",
  ),
  item(
    "country-mongolia",
    'countries',
    "Mongolia",
    'epic',
    "🇲🇳",
    "Many families in Mongolia live in round felt tents called gers and move with their horses across the grassy steppe. Mongolia has a lot of open land and very few people.",
    "Capital: Ulaanbaatar · Continent: Asia",
    "Say: mon-GOH-lee-uh",
  ),
  item(
    "country-fiji",
    'countries',
    "Fiji",
    'epic',
    "🇫🇯",
    "Fiji is made of more than three hundred islands in the warm Pacific Ocean. Its beaches have soft white sand and clear water full of colourful coral and fish.",
    "Capital: Suva · Continent: Oceania",
    "Say: FEE-jee",
  ),
  item(
    "country-bhutan",
    'countries',
    "Bhutan",
    'legendary',
    "🇧🇹",
    "Tiger's Nest is a monastery built on the side of a steep cliff in Bhutan. The Bhutan flag shows a thunder dragon, and the country has promised to keep most of its land covered in forest.",
    "Capital: Thimphu · Continent: Asia",
    "Say: boo-TAHN",
  ),
]
