import type { CollectionItem } from './item'
import { item } from './item'

// Gems & minerals (24). Photos: public/collection/<id>.jpg
export const GEMS: CollectionItem[] = [
  item(
    'quartz',
    'gems',
    'Quartz',
    'common',
    '🪨',
    'Quartz is one of the most common minerals on Earth. It often grows in six-sided crystal points that sparkle in sunlight.',
    'Found in: almost everywhere on Earth',
  ),
  item(
    'rose-quartz',
    'gems',
    'Rose quartz',
    'common',
    '💗',
    'Rose quartz gets its soft pink colour from tiny mineral traces inside it. People often carve it into hearts and smooth palm stones.',
    'Found in: Brazil and Madagascar',
  ),
  item(
    'amethyst',
    'gems',
    'Amethyst',
    'common',
    '💜',
    'Amethyst is purple quartz coloured by traces of iron. Long ago, people thought it could keep them safe on adventures.',
    'Found in: Brazil and Uruguay',
    'Say: am-uh-thist',
  ),
  item(
    'citrine',
    'gems',
    'Citrine',
    'common',
    '🟡',
    "Citrine is a sunny yellow quartz named after the citron fruit. Most citrine sold today started out as purple amethyst, heated until it turned gold.",
    'Found in: Brazil and Zambia',
  ),
  item(
    'agate',
    'gems',
    'Agate',
    'common',
    '🪨',
    'Agate forms in rings of colour, like a rainbow frozen in stone. Every agate has its own pattern, so no two are exactly alike.',
    'Found in: Brazil and Mexico',
  ),
  item(
    'jasper',
    'gems',
    'Jasper',
    'common',
    '🪨',
    'Jasper is a colourful stone that people have carved into beads and seals for thousands of years. Its swirling patterns can look like tiny landscapes.',
    'Found in: India and Madagascar',
  ),
  item(
    'obsidian',
    'gems',
    'Obsidian',
    'common',
    '⚫',
    'Obsidian is volcanic glass, made when hot lava cools very fast. It can be so smooth and sharp that ancient people shaped it into tools.',
    'Found in: volcanoes around the world',
  ),
  item(
    'pyrite',
    'gems',
    'Pyrite',
    'common',
    '🟨',
    "Pyrite is nicknamed fool's gold because it glitters just like real gold. It often forms in perfect little cube shapes.",
    'Found in: Spain and Peru',
  ),
  item(
    'malachite',
    'gems',
    'Malachite',
    'common',
    '🟢',
    'Malachite is a bright green stone with swirly bands, like tree rings. Ancient Egyptians ground it up to make green eye paint.',
    'Found in: the Democratic Republic of the Congo',
  ),
  item(
    'turquoise',
    'gems',
    'Turquoise',
    'common',
    '🩵',
    'Turquoise gets its blue-green colour from copper in the rock around it. People have carved it into jewellery for thousands of years.',
    'Found in: Iran and the south-western USA',
  ),
  item(
    'lapis-lazuli',
    'gems',
    'Lapis lazuli',
    'uncommon',
    '🔵',
    'Lapis lazuli is a deep blue rock speckled with gold flecks of pyrite. Painters once crushed it to make a brilliant blue paint.',
    'Found in: Afghanistan',
    'Say: LAP-iss LAZ-yoo-lee',
  ),
  item(
    'garnet',
    'gems',
    'Garnet',
    'uncommon',
    '🔴',
    'Garnet comes in almost every colour, though deep red is the most common. Its name comes from a word for pomegranate seeds, which it resembles.',
    'Found in: India and East Africa',
  ),
  item(
    'topaz',
    'gems',
    'Topaz',
    'uncommon',
    '🟠',
    'Topaz can be blue, pink, or golden yellow, and it is one of the harder gems around. It is the birthstone for November.',
    'Found in: Brazil and Sri Lanka',
  ),
  item(
    'aquamarine',
    'gems',
    'Aquamarine',
    'uncommon',
    '🩵',
    'Aquamarine means seawater in Latin, and its pale blue colour matches the name perfectly. Sailors once carried it as a good-luck charm at sea.',
    'Found in: Brazil and Pakistan',
  ),
  item(
    'peridot',
    'gems',
    'Peridot',
    'uncommon',
    '🟢',
    'Peridot is a lively green gem that forms deep underground, inside volcanic rock. Tiny bits of it have even been found inside meteorites from space.',
    'Found in: Arizona, USA and Myanmar',
  ),
  item(
    'tourmaline',
    'gems',
    'Tourmaline',
    'uncommon',
    '🌈',
    'Tourmaline comes in more colours than almost any other gem, sometimes several colours in one crystal. Some crystals are pink on one end and green on the other.',
    'Found in: Brazil and Nigeria',
    'Say: TOOR-ma-leen',
  ),
  item(
    'opal',
    'gems',
    'Opal',
    'uncommon',
    '⚪',
    'Opal can flash every colour of the rainbow when it catches the light. This sparkle happens because of tiny spheres of silica packed inside it.',
    'Found in: Australia',
  ),
  item(
    'emerald',
    'gems',
    'Emerald',
    'rare',
    '💚',
    'Emerald is a rich green gem, coloured by traces of chromium. It is often found with tiny natural marks inside, nicknamed its garden.',
    'Found in: Colombia and Zambia',
  ),
  item(
    'ruby',
    'gems',
    'Ruby',
    'rare',
    '❤️',
    'Ruby is a deep red gem, and its colour comes from a trace of chromium. It is one of the toughest gems, second only to diamond.',
    'Found in: Myanmar and Thailand',
  ),
  item(
    'sapphire',
    'gems',
    'Sapphire',
    'rare',
    '💙',
    'Sapphire is famous for its deep blue colour, but it can also be pink, yellow, or even colourless. It is the very same mineral as ruby, just a different colour.',
    'Found in: Sri Lanka and Australia',
  ),
  item(
    'gold-nugget',
    'gems',
    'Gold nugget',
    'rare',
    '🪙',
    'A gold nugget is a lump of pure gold found in rivers or rock, with no melting or shaping needed. Gold never rusts, so nuggets can shine for thousands of years.',
    'Found in: riverbeds and mines worldwide',
  ),
  item(
    'tanzanite',
    'gems',
    'Tanzanite',
    'epic',
    '🔵',
    'Tanzanite is a blue-purple gem found in only one place on Earth, near Mount Kilimanjaro. It was only discovered in 1967.',
    'Found in: Tanzania, only near Mount Kilimanjaro',
    'Say: tan-zuh-NITE',
  ),
  item(
    'alexandrite',
    'gems',
    'Alexandrite',
    'epic',
    '💚',
    'Alexandrite is a magic-trick gem: it looks green in daylight and red under warm indoor light. It was named after a Russian tsar.',
    'Found in: Russia and Sri Lanka',
    'Say: al-ex-AN-drite',
  ),
  item(
    'diamond',
    'gems',
    'Diamond',
    'legendary',
    '💎',
    'Diamond is the hardest natural material on Earth, formed under huge heat and pressure deep underground. Its name comes from a Greek word meaning unbreakable.',
    'Found in: South Africa and Russia',
  ),
]
