import type { CollectionItem } from './item'
import { item } from './item'

// Space (16).
export const SPACE: CollectionItem[] = [
  item(
    'moon',
    'space',
    'Moon',
    'common',
    '🌙',
    "The Moon is Earth's only natural satellite and the closest object in space to us. Its gravity pulls on the oceans and creates our tides.",
    'Orbits: Earth',
  ),
  item(
    'mars',
    'space',
    'Mars',
    'common',
    '🔴',
    'Mars is called the Red Planet because iron minerals on its surface have rusted. It is home to the tallest volcano in the solar system, Olympus Mons.',
    'Orbits: the Sun, 4th planet',
  ),
  item(
    'earth',
    'space',
    'Earth',
    'common',
    '🌍',
    'Earth is the only planet we know of with liquid water on its surface and life. From space, it looks like a blue marble because oceans cover most of it.',
    'Orbits: the Sun, 3rd planet',
  ),
  item(
    'sun',
    'space',
    'Sun',
    'common',
    '☀️',
    'The Sun is a giant ball of glowing gas that gives Earth its light and warmth. It is so big that about 1.3 million Earths could fit inside it.',
    'Located: centre of our solar system',
  ),
  item(
    'venus',
    'space',
    'Venus',
    'common',
    '🟡',
    'Venus is the hottest planet, even hotter than Mercury, because thick clouds trap heat like a blanket. A single day on Venus lasts longer than its whole year.',
    'Orbits: the Sun, 2nd planet',
  ),
  item(
    'jupiter',
    'space',
    'Jupiter',
    'common',
    '🟠',
    'Jupiter is the biggest planet in the solar system, so huge that all the other planets could fit inside it. Its Great Red Spot is a giant storm bigger than Earth.',
    'Orbits: the Sun, 5th planet',
  ),
  item(
    'mercury',
    'space',
    'Mercury',
    'uncommon',
    '⚪',
    'Mercury is the smallest planet and the closest to the Sun, zooming all the way around it in just 88 days. It has almost no atmosphere, so its temperature swings wildly.',
    'Orbits: the Sun, 1st planet',
  ),
  item(
    'saturn',
    'space',
    'Saturn',
    'uncommon',
    '🪐',
    "Saturn's beautiful rings are made mostly of chunks of ice and rock, some tiny and some as big as a house. It has more than 140 known moons.",
    'Orbits: the Sun, 6th planet',
  ),
  item(
    'neptune',
    'space',
    'Neptune',
    'uncommon',
    '🔵',
    'Neptune is the windiest planet, with storms racing faster than the speed of sound. It is so far from the Sun that its year lasts 165 Earth years.',
    'Orbits: the Sun, 8th planet',
  ),
  item(
    'uranus',
    'space',
    'Uranus',
    'uncommon',
    '🔵',
    'Uranus spins almost on its side, so it rolls around the Sun like a tipped-over ball. It looks pale blue because of methane gas in its atmosphere.',
    'Orbits: the Sun, 7th planet',
  ),
  item(
    'pluto',
    'space',
    'Pluto',
    'uncommon',
    '⚪',
    'Pluto is a dwarf planet in the icy Kuiper Belt, far beyond Neptune. It has a huge heart-shaped patch of frozen nitrogen that shows up clearly in photos.',
    'Orbits: the Sun, a dwarf planet',
  ),
  item(
    'comet',
    'space',
    'Comet',
    'rare',
    '☄️',
    'A comet is a ball of ice, dust, and rock that grows a glowing tail when it flies close to the Sun. Some comets take thousands of years to complete one loop.',
    'Orbits: the Sun in a long loop',
  ),
  item(
    'orion-nebula',
    'space',
    'Orion Nebula',
    'rare',
    '🌌',
    'The Orion Nebula is a giant cloud of gas and dust where new stars are being born right now. You can spot it with just your eyes, below the three stars of Orion’s belt.',
    'Located: the constellation Orion',
    'Say: oh-RY-un',
  ),
  item(
    'milky-way',
    'space',
    'Milky Way',
    'rare',
    '🌌',
    'The Milky Way is our home galaxy, home to our Sun and hundreds of billions of other stars. On a clear dark night, you can see it as a hazy band across the sky.',
    'Located: our home galaxy',
  ),
  item(
    'europa',
    'space',
    'Europa',
    'epic',
    '🌕',
    "Europa is one of Jupiter's moons, and it hides a deep ocean of liquid water under its icy shell. Scientists think it could be one of the best places to search for life beyond Earth.",
    'Orbits: Jupiter',
  ),
  item(
    'andromeda-galaxy',
    'space',
    'Andromeda galaxy',
    'legendary',
    '🌌',
    'The Andromeda galaxy is our nearest large galactic neighbour, so far away its light takes 2.5 million years to reach us. It contains roughly a trillion stars.',
    'Located: 2.5 million light-years away',
    'Say: an-DROM-eh-duh',
  ),
  // --- Round 16 additions
  item(
    'international-space-station',
    'space',
    'International Space Station',
    'common',
    '🛰️',
    'The International Space Station circles the Earth about every 90 minutes, so the crew sees many sunrises each day. People have lived on board without a break for over twenty years.',
    'Orbits: Earth',
  ),
  item(
    'astronaut-spacewalk',
    'space',
    'Astronaut on a spacewalk',
    'common',
    '👨‍🚀',
    'On a spacewalk, an astronaut wears a spacesuit that works like a tiny personal spaceship. It gives air to breathe and protects against freezing and boiling heat.',
    'Located: outside a spacecraft, in orbit',
  ),
  item(
    'rocket-launch',
    'space',
    'Rocket launch',
    'common',
    '🚀',
    'A rocket must travel very fast, about eight kilometres every second, to stay in orbit around Earth. The Saturn V rocket that took people to the Moon was taller than a 35-storey building.',
    'Located: launch pads on Earth',
  ),
  item(
    'io',
    'space',
    'Io',
    'uncommon',
    '🌋',
    'Io, a moon of Jupiter, has more active volcanoes than anywhere else we know. Some of them shoot plumes of gas and dust hundreds of kilometres high.',
    'Orbits: Jupiter',
    'Say: EYE-oh',
  ),
  item(
    'titan',
    'space',
    'Titan',
    'uncommon',
    '🟠',
    'Titan is the biggest moon of Saturn and has a thick, orange, hazy sky. It has rivers and lakes too, but they are filled with liquid natural gas instead of water.',
    'Orbits: Saturn',
  ),
  item(
    'pleiades-star-cluster',
    'space',
    'Pleiades star cluster',
    'uncommon',
    '✨',
    'The Pleiades is a group of young, hot, blue stars that you can see in the night sky without a telescope. Many people call it the Seven Sisters.',
    'Located: in the constellation Taurus',
    'Say: PLEE-uh-deez',
  ),
  item(
    'pillars-of-creation',
    'space',
    'Pillars of Creation',
    'rare',
    '🌫️',
    'The Pillars of Creation are giant towers of gas and dust where new stars are being born. They are so tall that light takes years to travel from the top to the bottom.',
    'Located: the Eagle Nebula',
  ),
  item(
    'hubble-space-telescope',
    'space',
    'Hubble Space Telescope',
    'rare',
    '🔭',
    'The Hubble Space Telescope has circled the Earth since 1990, taking sharp pictures high above the blurry air. It has shown us thousands of galaxies, far away and long ago.',
    'Orbits: Earth',
  ),
  item(
    'black-hole',
    'space',
    'Black hole',
    'epic',
    '🕳️',
    'This is the first picture ever taken of a black hole, at the heart of a galaxy called M87. Its pull is so strong that not even light can escape from it.',
    'Located: the centre of the galaxy M87',
  ),
  item(
    'james-webb-space-telescope',
    'space',
    'James Webb Space Telescope',
    'epic',
    '🪞',
    'The James Webb Space Telescope has a golden mirror made of eighteen hexagon-shaped pieces. It floats about one and a half million kilometres from Earth and sees the faint glow of the first galaxies.',
    'Orbits: the Sun, far beyond the Moon',
  ),
]
